import = ["~/.config/alacritty/rose-pine.toml"]

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
decorations = "None"

[font]
size = 13

normal.family = "FiraCode Nerd Font Mono"
normal.style = "Retina"

bold.family = "FiraCode Nerd Font Mono"
bold.style = "Bold"

italic.family = "FiraCode Nerd Font Mono"
italic.style = "Italic"

bold_italic.family = "FiraCode Nerd Font Mono"
bold_italic.style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = true

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "Return"
mods = "Command"
