
[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
decorations = "None"

[font]
size = 13

normal.family = "JetBrainsMono NF"
normal.style = "Regular"

bold.family = "JetBrainsMono NF"
bold.style = "Bold"

italic.family = "JetBrainsMono NF"
italic.style = "Italic"

bold_italic.family = "JetBrainsMono NF"
bold_italic.style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = true

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "Return"
mods = "Command"

[mouse]
hide_when_typing = false

[general]
import = ["~/.config/alacritty/rose-pine.toml"]
