import = ["~/.config/alacritty/tokyo-night.toml"]

[window]
dynamic_padding = true
decorations = "None"

[font]
size = 13

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Retina"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = true

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "Return"
mods = "Command"
