cask_args appdir: '/Applications'
tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'homebrew/cask-drivers'
tap 'homebrew/cask-fonts'
tap 'homebrew/core'

brew 'mas'
brew 'zsh'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'neovim'
brew 'autojump'
brew 'fzf'
brew 'lazygit'
brew 'wget'
brew 'the_silver_searcher'
brew 'ripgrep'
brew 'yabai'
brew 'skhd'
brew 'htop-osx'
brew 'ruby-build'
brew 'rbenv'
brew 'python'
brew 'pipenv'
brew 'nmap'
brew 'unrar'
brew 'gh'
brew 'awscli'
brew 'terraform'
brew 'mise'
brew 'awslogs'
brew 'jq'
brew 'fswatch'
brew 'go'

# CASKS (GUI APPS)

cask 'alacritty'
cask 'font-fira-mono'
cask 'font-fira-mono-nerd-font'
cask 'font-fira-code'
cask 'font-fira-code-nerd-font'
cask 'raycast'
cask 'google-chrome'
cask 'google-chrome-canary'
cask 'firefox'
cask 'firefox-developer-edition'
cask 'brave-browser'
cask 'slack'
cask 'zoom'
cask 'krisp'
cask 'notion'
cask 'notion-calendar'
cask 'coconutbattery'
cask 'vlc'
cask 'webtorrent'
cask 'visual-studio-code'
cask 'gpg-suite'
cask 'docker'
cask 'signal'
cask 'obsidian'
cask 'calibre'
cask 'bruno'
cask 'lastfm'

# MAC APP STORE APPS
mas 'Keynote', id: 409183694
mas 'Pixelmator', id: 407963104
