cask_args appdir: '/Applications'
tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'homebrew/cask-drivers'
tap 'homebrew/cask-fonts'
tap 'homebrew/core'

brew 'mas'
brew 'zsh'
brew 'autojump'
brew 'wget'
brew 'the_silver_searcher'
brew 'python'
brew 'vim'
brew 'macvim'
brew 'tmux'
brew 'htop-osx'
brew 'tig'
brew 'ruby-build'
brew 'rbenv'
brew 'python'
brew 'pipenv'
brew 'nmap'
brew 'reattach-to-user-namespace'
brew 'unrar'
brew 'hub'
brew 'gh'
brew 'neovim'
brew 'fzf'
brew 'awscli'
brew 'terraform'
brew 'Schniz/tap/fnm'
brew 'awslogs'
brew 'jq'
brew 'tmuxinator'

# CASKS (GUI APPS)

cask 'alfred'
cask 'google-chrome'
cask 'google-chrome-canary'
cask 'firefox'
cask 'firefox-developer-edition'
cask 'iterm2'
cask 'moom'
# cask 'dash'
cask 'slack'
cask 'keybase'
cask 'coconutbattery'
cask 'ngrok'
cask 'vlc'
cask 'cyberduck'
cask 'insomnia'
cask 'webtorrent'
cask 'visual-studio-code'
cask 'recordit'
cask 'font-fira-mono'
cask 'font-fira-mono-nerd-font'
cask 'krisp'
cask 'gpg-suite'
cask 'notion'
cask 'docker'
cask 'brave-browser'
cask 'signal'

# MAC APP STORE APPS
mas 'Keynote', id: 409183694
mas 'Pixelmator', id: 407963104
