# editor completions
"$schema" = 'https://starship.rs/config-schema.json'

# add blank line between prompts
add_newline = true

[character]
# success_symbol = '[➜](bold green)'
# error_symbol = '[➜](bold red)'

[aws]
disabled = true

[package]
disabled = true
