#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding in px
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_gap 2

# mouse
yabai -m config mouse_follows_focus on
# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m config mouse_drop_action swap

# space rules
yabai -m rule --add app="^Firefox" space=1
yabai -m rule --add app="^Google Chrome" space=2
yabai -m rule --add app="^Alacritty" space=2
yabai -m rule --add app="^Ghostty" space=2
yabai -m rule --add app="^Calendar" space=3
yabai -m rule --add app="^Slack" space=4
yabai -m rule --add app="^Mail" space=5
yabai -m rule --add app="^Signal" space=5
yabai -m rule --add app="^Music" space=6

# manage off rules
yabai -m rule --add app="^Last.fm" manage=off
yabai -m rule --add app="^Archetype Gojira" manage=off
